### ISSUE TITLE
No space left on device

### ISSUE THREAD

**Issue by matthiasbeyer** [ipfs/ipfs#213]
Hi,

I just experienced this on one of my testing VMs:

```
 537.96 MB / 1.69 GB [======================>-------------------------------------------------]  31.07% 2h17m43s20:57:34.442 ERROR commands/h: open /home/clouduser/.ipfs/blocks/CIQFD/put-263871557: no space left on device client.go:247
```

but:

```
$ df -h
Filesystem      Size  Used Avail Use% Mounted on
/dev/vda1       9.9G  5.7G  3.7G  61% /
udev             10M     0   10M   0% /dev
tmpfs           201M   25M  176M  13% /run
tmpfs           501M     0  501M   0% /dev/shm
tmpfs           5.0M     0  5.0M   0% /run/lock
tmpfs           501M     0  501M   0% /sys/fs/cgroup
tmpfs           101M     0  101M   0% /run/user/1001
```

and:

```
[...]

gx/ipfs/QmRQhVisS8dmPbjBUthVkenn81pBxrx1GxE281csJhm2vL/go-msgio.ReadLen(0x7f3b889083a8, 0xc42771d300, 0xc438ef0220, 0x4, 0x4, 0x9df84c, 0xc423b72c38, 0xc423b72c48)
        /builds/distributions/dists/go-ipfs/gopath/src/gx/ipfs/QmRQhVisS8dmPbjBUthVkenn81pBxrx1GxE281csJhm2vL/go-msgio/num.go:27 +0x74
gx/ipfs/QmRQhVisS8dmPbjBUthVkenn81pBxrx1GxE281csJhm2vL/go-msgio.(*reader).nextMsgLen(0xc438346280, 0x10e3448, 0xc438ef0228, 0xc423b72c78)
        /builds/distributions/dists/go-ipfs/gopath/src/gx/ipfs/QmRQhVisS8dmPbjBUthVkenn81pBxrx1GxE281csJhm2vL/go-msgio/msgio.go:163 +0x85
gx/ipfs/QmRQhVisgx/ipfs/QmRQhVisS8dmPbjBUthVkenn81pBxrx1GxE281csJhm2vL/go-msgio.ReadLen(0x7f3b889083a8, 0xc42771d300, 0xc438ef0220, 0x4, 0x4, 0x9df84c, 0xc423b72c38, 0xc423b72c48)
        /builds/distributions/dists/go-ipfs/gopath/src/gx/ipfs/QmRQhVisS8dmPbjBUthVkenn81pBxrx1GxE281csJhm2vL/go-msgio/num.go:27 +0x74
gx/ipfs/QmRQhVisS8dmPbjBUthVkenn81pBxrx1GxE281csJhm2vL/go-msgio.(*reader).nextMsgLen(0xc438346280, 0x10e3448, 0xc438ef0228, 0xc423b72c78)
        /builds/distributions/dists/go-ipfs/gopath/src/gx/ipfs/QmRQhVisS8dmPbjBUthVkenn81pBxrx1GxE281csJhm2vL/go-msgio/msgio.go:163 +0x85
gx/ipfs/QmRQhVisS8dmPbjBUthVkenn81pBxrx1GxE281csJhm2vL/go-msgio.(*reader).NextMsgLen(0xc438346280, 0x0, 0x0, 0x0)
        /builds/distributions/dists/go-ipfs/gopath/src/gx/ipfs/QmRQhVisS8dmPbjBUthVkenn81pBxrx1GxE281csJhm2vL/go-msgio/msgio.go:158 +0x8e
gx/ipfs/QmVjz1uf6U3sVQ5DbWWj7ktTtDd4GgsptYc7FBp33nWE53/go-libp2p-secio.(*etmReader).Read(0xc435527560, 0xc43dd75000, 0x1000, 0x1000, 0x0, 0x0, 0x0)
        /builds/distributions/dists/go-ipfs/gopath/src/gx/ipfs/QmVjz1uf6U3sVQ5DbWWj7ktTtDd4GgsptYc7FBp33nWE53/go-libp2p-secio/rw.go:164 +0x108
gx/ipfs/QmRQhVisS8dmPbjBUthVkenn81pBxrx1GxE281csJhm2vL/go-msgio.(*readWriter).Read(0xc42f7f90e0, 0xc43dd75000, 0x1000, 0x1000, 0xc43801f658, 0xffffffff, 0x0)
        <autogenerated>:16 +0x6b
gx/ipfs/QmVCe3SNMjkcPgnpFhZs719dheq6xE7gJwjzV7aWcUM4Ms/go-libp2p/p2p/net/conn.(*secureConn).Read(0xc4368ce040, 0xc43dd75000, 0x1000, 0x1000, 0xc42bb55d40, 0xc4370f9ee0, 0xc)
        /builds/distributions/dists/go-ipfs/gopath/src/gx/ipfs/QmVCe3SNMjkcPgnpFhZs719dheq6xE7gJwjzV7aWcUM4Ms/go-libp2p/p2p/net/conn/secure_conn.go:113 +0x66
bufio.(*Reader).fill(0xc43afba720)
        /home/whyrusleeping/go/src/bufio/bufio.go:97 +0x10c
bufio.(*Reader).Read(0xc43afba720, 0xc4370f9ee0, 0xc, 0xc, 0x10, 0xc43d7a5210, 0x0)
        /home/whyrusleeping/go/src/bufio/bufio.go:209 +0x1bc
io.ReadAtLeast(0x10dbe20, 0xc43afba720, 0xc4370f9ee0, 0xc, 0xc, 0xc, 0xc, 0x0, 0x0)
        /home/whyrusleeping/go/src/io/io.go:307 +0xa4
io.ReadFull(0x10dbe20, 0xc43afba720, 0xc4370f9ee0, 0xc, 0xc, 0xc, 0x0, 0x0)
        /home/whyrusleeping/go/src/io/io.go:325 +0x58
gx/ipfs/QmZ8MMKFwA95viWULoSYFZpA4kdFa8idmFSrP12YJwjjaL/yamux.(*Session).recvLoop(0xc43801f600, 0x0, 0x0)
        /builds/distributions/dists/go-ipfs/gopath/src/gx/ipfs/QmZ8MMKFwA95viWULoSYFZpA4kdFa8idmFSrP12YJwjjaL/yamux/session.go:411 +0xf3
gx/ipfs/QmZ8MMKFwA95viWULoSYFZpA4kdFa8idmFSrP12YJwjjaL/yamux.(*Session).recv(0xc43801f600)
        /builds/distributions/dists/go-ipfs/gopath/src/gx/ipfs/QmZ8MMKFwA95viWULoSYFZpA4kdFa8idmFSrP12YJwjjaL/yamux/session.go:399 +0x2b
created by gx/ipfs/QmZ8MMKFwA95viWULoSYFZpA4kdFa8idmFSrP12YJwjjaL/yamux.newSession
        /builds/distributions/dists/go-ipfs/gopath/src/gx/ipfs/QmZ8MMKFwA95viWULoSYFZpA4kdFa8idmFSrP12YJwjjaL/yamux/session.go:104 +0x43d

goroutine 32971028 [select]:
github.com/ipfs/go-ipfs/exchange/bitswap.(*msgQueue).runQueue(0xc4360c6660, 0x10e8aa0, 0xc420017040)
        /builds/distributions/dists/go-ipfs/gopath/src/github.com/ipfs/go-ipfs/exchange/bitswap/wantmanager.go:166 +0x1c9
created by github.com/ipfs/go-ipfs/exchange/bitswap.(*WantManager).startPeerHandler
        /builds/distributions/dists/go-ipfs/gopath/src/github.com/ipfs/go-ipfs/exchange/bitswap/wantmanager.go:139 +0x388

goroutine 35807461 [select]:
github.com/ipfs/go-ipfs/exchange/bitswap.(*msgQueue).runQueue(0xc433927c20, 0x10e8aa0, 0xc420017040)
        /builds/distributions/dists/go-ipfs/gopath/src/github.com/ipfs/go-ipfs/exchange/bitswap/wantmanager.go:166 +0x1c9
created by github.com/ipfs/go-ipfs/exchange/bitswap.(*WantManager).startPeerHandler
        /builds/distributions/dists/go-ipfs/gopath/src/github.com/ipfs/go-ipfs/exchange/bitswap/wantmanager.go:139 +0x388

goroutine 36021518 [syscall]:
syscall.Syscall6(0xe8, 0x60, 0xc4329184f4, 0x20, 0x270f, 0x0, 0x0, 0x1abf9552, 0xc427809958, 0x63a722)
        /home/whyrusleeping/go/src/syscall/asm_linux_amd64.s:44 +0x5
syscall.EpollWait(0x60, 0xc4329184f4, 0x20, 0x20, 0x270f, 0x11c1b60, 0x2540b14a1, 0xc4278099c8)
        /home/whyrusleeping/go/src/syscall/zsyscall_linux_amd64.go:365 +0x77
gx/ipfs/QmaaC9QMYTQHCbMq3Ebr3uMaAR2ev4AVqMmsJpgQijAZbJ/go-reuseport/poll.(*Poller).WaitWrite(0xc4329184e0, 0xecfcd5b67, 0xc41abec5f3, 0x11c1b60, 0xc42be62601, 0x5e)
        /builds/distributions/dists/go-ipfs/gopath/src/gx/ipfs/QmaaC9QMYTQHCbMq3Ebr3uMaAR2ev4AVqMmsJpgQijAZbJ/go-reuseport/poll/poll_linux.go:43 +0x80
gx/ipfs/QmaaC9QMYTQHCbMq3Ebr3uMaAR2ev4AVqMmsJpgQijAZbJ/go-reuseport.connect(0x5e, 0x10deba0, 0xc433eaa280, 0xecfcd5b67, 0x1abec5f3, 0x11c1b60, 0x0, 0x0)
        /builds/distributions/dists/go-ipfs/gopath/src/gx/ipfs/QmaaC9QMYTQHCbMq3Ebr3uMaAR2ev4AVqMmsJpgQijAZbJ/go-reuseport/impl_unix.go:323 +0x158
gx/ipfs/QmaaC9QMYTQHCbMq3Ebr3uMaAR2ev4AVqMmsJpgQijAZbJ/go-reuseport.dial(0x2540be400, 0x0, 0x0, 0x0, 0x10e2860, 0xc4202c4fc0, 0x0, 0x0, 0x0, 0x0, ...)
        /builds/distributions/dists/go-ipfs/gopath/src/gx/ipfs/QmaaC9QMYTQHCbMq3Ebr3uMaAR2ev4AVqMmsJpgQijAZbJ/go-reuseport/impl_unix.go:138 +0x3cf
gx/ipfs/QmaaC9QMYTQHCbMq3Ebr3uMaAR2ev4AVqMmsJpgQijAZbJ/go-reuseport.(*Dialer).Dial(0xc4203441d8, 0xc42be626e0, 0x4, 0xc433eaa220, 0x12, 0x12, 0x0, 0x0, 0xc433eaa180)
        /builds/distributions/dists/go-ipfs/gopath/src/gx/ipfs/QmaaC9QMYTQHCbMq3Ebr3uMaAR2ev4AVqMmsJpgQijAZbJ/go-reuseport/interface.go:98 +0x99
gx/ipfs/QmWzfrG1PUeF8mDpYfNsRL3wh5Rkgnp68LAWUB2bhuDWRL/go-libp2p-transport.(*tcpDialer).reuseDial(0xc4203441c0, 0x10ec0c0, 0xc430285920, 0xc430285920, 0xc433eaa001, 0x0, 0x2)
        /builds/distributions/dists/go-ipfs/gopath/src/gx/ipfs/QmWzfrG1PUeF8mDpYfNsRL3wh5Rkgnp68LAWUB2bhuDWRL/go-libp2p-transport/tcp.go:187 +0x1ce
gx/ipfs/QmWzfrG1PUeF8mDpYfNsRL3wh5Rkgnp68LAWUB2bhuDWRL/go-libp2p-transport.(*tcpDialer).Dial(0xc4203441c0, 0x10ec0c0, 0xc430285920, 0x10e2020, 0xc4203441c0, 0xc420766688, 0x438173)
        /builds/distributions/dists/go-ipfs/gopath/src/gx/ipfs/QmWzfrG1PUeF8mDpYfNsRL3wh5Rkgnp68LAWUB2bhuDWRL/go-libp2p-transport/tcp.go:163 +0x4f
gx/ipfs/QmVCe3SNMjkcPgnpFhZs719dheq6xE7gJwjzV7aWcUM4Ms/go-libp2p/p2p/net/conn.(*Dialer).rawConnDial(0xc42004b360, 0x10e8aa0, 0xc424671500, 0x10ec0c0, 0xc430285920, 0xc443ae6690, 0x22, 0xc42d42da00, 0x0, 0x1, ...)
        /builds/distributions/dists/go-ipfs/gopath/src/gx/ipfs/QmVCe3SNMjkcPgnpFhZs719dheq6xE7gJwjzV7aWcUM4Ms/go-libp2p/p2p/net/conn/dial.go:155 +0x2c2
gx/ipfs/QmVCe3SNMjkcPgnpFhZs719dheq6xE7gJwjzV7aWcUM4Ms/go-libp2p/p2p/net/conn.(*Dialer).Dial.func1(0xc42663b9e0, 0x10e8aa0, 0xc424671500, 0xc42004b360, 0x10ec0c0, 0xc430285920, 0xc443ae6690, 0x22, 0xc42be625a0, 0xc42be62580)
        /builds/distributions/dists/go-ipfs/gopath/src/gx/ipfs/QmVCe3SNMjkcPgnpFhZs719dheq6xE7gJwjzV7aWcUM4Ms/go-libp2p/p2p/net/conn/dial.go:57 +0xd5
created by gx/ipfs/QmVCe3SNMjkcPgnpFhZs719dheq6xE7gJwjzV7aWcUM4Ms/go-libp2p/p2p/net/conn.(*Dialer).Dial
        /builds/distributions/dists/go-ipfs/gopath/src/gx/ipfs/QmVCe3SNMjkcPgnpFhZs719dheq6xE7gJwjzV7aWcUM4Ms/go-libp2p/p2p/net/conn/dial.go:103 +0x359

goroutine 24191161 [select, 14 minutes]:
gx/ipfs/QmX6DhWrpBB5NtadXmPSXYNdVvuLfJXoFNMvUMoVvP5UJa/go-context/io.(*ctxReader).Read(0xc4395d83c0, 0xc433d85000, 0x1000, 0x1000, 0xd3a2b0, 0xc41ebbd9e0, 0x0)
        /builds/distributions/dists/go-ipfs/gopath/src/gx/ipfs/QmX6DhWrpBB5NtadXmPSXYNdVvuLfJXoFNMvUMoVvP5UJa/go-context/io/ctxio.go:113 +0x2b4
bufio.(*Reader).fill(0xc423e3d1a0)
        /home/whyrusleeping/go/src/bufio/bufio.go:97 +0x10c
bufio.(*Reader).ReadByte(0xc423e3d1a0, 0x0, 0x58, 0x68)
        /home/whyrusleeping/go/src/bufio/bufio.go:231 +0x51
encoding/binary.ReadUvarint(0x10dbde0, 0xc423e3d1a0, 0x0, 0x10e8aa0, 0x97a)
        /home/whyrusleeping/go/src/encoding/binary/varint.go:110 +0x4a
gx/ipfs/QmZ4Qi3GaRbjcx28Sme5eMH7RQjGkt8wHxt2a65oLaeFEV/gogo-protobuf/io.(*varintReader).ReadMsg(0xc433010b40, 0x10e4fe0, 0xc44884c380, 0x0, 0x0)
        /builds/distributions/dists/go-ipfs/gopath/src/gx/ipfs/QmZ4Qi3GaRbjcx28Sme5eMH7RQjGkt8wHxt2a65oLaeFEV/gogo-protobuf/io/varint.go:105 +0x3e
github.com/ipfs/go-ipfs/routing/dht.(*IpfsDHT).handleNewMessage(0xc4200de6e0, 0x10e75e0, 0xc433010b00)
        /builds/distributions/dists/go-ipfs/gopath/src/github.com/ipfs/go-ipfs/routing/dht/dht_net.go:37 +0x48a
created by github.com/ipfs/go-ipfs/routing/dht.(*IpfsDHT).handleNewStream
        /builds/distributions/dists/go-ipfs/gopath/src/github.com/ipfs/go-ipfs/routing/dht/dht_net.go:21 +0x53S8dmPbjBUthVkenn81pBxrx1GxE281csJhm2vL/go-msgio.(*reader).NextMsgLen(0xc438346280, 0x0, 0x0, 0x0)
        /builds/distributions/dists/go-ipfs/gopath/src/gx/ipfs/QmRQhVisS8dmPbjBUthVkenn81pBxrx1GxE281csJhm2vL/go-msgio/msgio.go:158 +0x8e
gx/ipfs/QmVjz1uf6U3sVQ5DbWWj7ktTtDd4GgsptYc7FBp33nWE53/go-libp2p-secio.(*etmReader).Read(0xc435527560, 0xc43dd75000, 0x1000, 0x1000, 0x0, 0x0, 0x0)
        /builds/distributions/dists/go-ipfs/gopath/src/gx/ipfs/QmVjz1uf6U3sVQ5DbWWj7ktTtDd4GgsptYc7FBp33nWE53/go-libp2p-secio/rw.go:164 +0x108
gx/ipfs/QmRQhVisS8dmPbjBUthVkenn81pBxrx1GxE281csJhm2vL/go-msgio.(*readWriter).Read(0xc42f7f90e0, 0xc43dd75000, 0x1000, 0x1000, 0xc43801f658, 0xffffffff, 0x0)
        <autogenerated>:16 +0x6b
gx/ipfs/QmVCe3SNMjkcPgnpFhZs719dheq6xE7gJwjzV7aWcUM4Ms/go-libp2p/p2p/net/conn.(*secureConn).Read(0xc4368ce040, 0xc43dd75000, 0x1000, 0x1000, 0xc42bb55d40, 0xc4370f9ee0, 0xc)
        /builds/distributions/dists/go-ipfs/gopath/src/gx/ipfs/QmVCe3SNMjkcPgnpFhZs719dheq6xE7gJwjzV7aWcUM4Ms/go-libp2p/p2p/net/conn/secure_conn.go:113 +0x66
bufio.(*Reader).fill(0xc43afba720)
        /home/whyrusleeping/go/src/bufio/bufio.go:97 +0x10c
bufio.(*Reader).Read(0xc43afba720, 0xc4370f9ee0, 0xc, 0xc, 0x10, 0xc43d7a5210, 0x0)
        /home/whyrusleeping/go/src/bufio/bufio.go:209 +0x1bc
io.ReadAtLeast(0x10dbe20, 0xc43afba720, 0xc4370f9ee0, 0xc, 0xc, 0xc, 0xc, 0x0, 0x0)
        /home/whyrusleeping/go/src/io/io.go:307 +0xa4
io.ReadFull(0x10dbe20, 0xc43afba720, 0xc4370f9ee0, 0xc, 0xc, 0xc, 0x0, 0x0)
        /home/whyrusleeping/go/src/io/io.go:325 +0x58
gx/ipfs/QmZ8MMKFwA95viWULoSYFZpA4kdFa8idmFSrP12YJwjjaL/yamux.(*Session).recvLoop(0xc43801f600, 0x0, 0x0)
        /builds/distributions/dists/go-ipfs/gopath/src/gx/ipfs/QmZ8MMKFwA95viWULoSYFZpA4kdFa8idmFSrP12YJwjjaL/yamux/session.go:411 +0xf3
gx/ipfs/QmZ8MMKFwA95viWULoSYFZpA4kdFa8idmFSrP12YJwjjaL/yamux.(*Session).recv(0xc43801f600)
        /builds/distributions/dists/go-ipfs/gopath/src/gx/ipfs/QmZ8MMKFwA95viWULoSYFZpA4kdFa8idmFSrP12YJwjjaL/yamux/session.go:399 +0x2b
created by gx/ipfs/QmZ8MMKFwA95viWULoSYFZpA4kdFa8idmFSrP12YJwjjaL/yamux.newSession
        /builds/distributions/dists/go-ipfs/gopath/src/gx/ipfs/QmZ8MMKFwA95viWULoSYFZpA4kdFa8idmFSrP12YJwjjaL/yamux/session.go:104 +0x43d

goroutine 32971028 [select]:
github.com/ipfs/go-ipfs/exchange/bitswap.(*msgQueue).runQueue(0xc4360c6660, 0x10e8aa0, 0xc420017040)
        /builds/distributions/dists/go-ipfs/gopath/src/github.com/ipfs/go-ipfs/exchange/bitswap/wantmanager.go:166 +0x1c9
created by github.com/ipfs/go-ipfs/exchange/bitswap.(*WantManager).startPeerHandler
        /builds/distributions/dists/go-ipfs/gopath/src/github.com/ipfs/go-ipfs/exchange/bitswap/wantmanager.go:139 +0x388

goroutine 35807461 [select]:
github.com/ipfs/go-ipfs/exchange/bitswap.(*msgQueue).runQueue(0xc433927c20, 0x10e8aa0, 0xc420017040)
        /builds/distributions/dists/go-ipfs/gopath/src/github.com/ipfs/go-ipfs/exchange/bitswap/wantmanager.go:166 +0x1c9
created by github.com/ipfs/go-ipfs/exchange/bitswap.(*WantManager).startPeerHandler
        /builds/distributions/dists/go-ipfs/gopath/src/github.com/ipfs/go-ipfs/exchange/bitswap/wantmanager.go:139 +0x388

goroutine 36021518 [syscall]:
syscall.Syscall6(0xe8, 0x60, 0xc4329184f4, 0x20, 0x270f, 0x0, 0x0, 0x1abf9552, 0xc427809958, 0x63a722)
        /home/whyrusleeping/go/src/syscall/asm_linux_amd64.s:44 +0x5
syscall.EpollWait(0x60, 0xc4329184f4, 0x20, 0x20, 0x270f, 0x11c1b60, 0x2540b14a1, 0xc4278099c8)
        /home/whyrusleeping/go/src/syscall/zsyscall_linux_amd64.go:365 +0x77
gx/ipfs/QmaaC9QMYTQHCbMq3Ebr3uMaAR2ev4AVqMmsJpgQijAZbJ/go-reuseport/poll.(*Poller).WaitWrite(0xc4329184e0, 0xecfcd5b67, 0xc41abec5f3, 0x11c1b60, 0xc42be62601, 0x5e)
        /builds/distributions/dists/go-ipfs/gopath/src/gx/ipfs/QmaaC9QMYTQHCbMq3Ebr3uMaAR2ev4AVqMmsJpgQijAZbJ/go-reuseport/poll/poll_linux.go:43 +0x80
gx/ipfs/QmaaC9QMYTQHCbMq3Ebr3uMaAR2ev4AVqMmsJpgQijAZbJ/go-reuseport.connect(0x5e, 0x10deba0, 0xc433eaa280, 0xecfcd5b67, 0x1abec5f3, 0x11c1b60, 0x0, 0x0)
        /builds/distributions/dists/go-ipfs/gopath/src/gx/ipfs/QmaaC9QMYTQHCbMq3Ebr3uMaAR2ev4AVqMmsJpgQijAZbJ/go-reuseport/impl_unix.go:323 +0x158
gx/ipfs/QmaaC9QMYTQHCbMq3Ebr3uMaAR2ev4AVqMmsJpgQijAZbJ/go-reuseport.dial(0x2540be400, 0x0, 0x0, 0x0, 0x10e2860, 0xc4202c4fc0, 0x0, 0x0, 0x0, 0x0, ...)
        /builds/distributions/dists/go-ipfs/gopath/src/gx/ipfs/QmaaC9QMYTQHCbMq3Ebr3uMaAR2ev4AVqMmsJpgQijAZbJ/go-reuseport/impl_unix.go:138 +0x3cf
gx/ipfs/QmaaC9QMYTQHCbMq3Ebr3uMaAR2ev4AVqMmsJpgQijAZbJ/go-reuseport.(*Dialer).Dial(0xc4203441d8, 0xc42be626e0, 0x4, 0xc433eaa220, 0x12, 0x12, 0x0, 0x0, 0xc433eaa180)
        /builds/distributions/dists/go-ipfs/gopath/src/gx/ipfs/QmaaC9QMYTQHCbMq3Ebr3uMaAR2ev4AVqMmsJpgQijAZbJ/go-reuseport/interface.go:98 +0x99
gx/ipfs/QmWzfrG1PUeF8mDpYfNsRL3wh5Rkgnp68LAWUB2bhuDWRL/go-libp2p-transport.(*tcpDialer).reuseDial(0xc4203441c0, 0x10ec0c0, 0xc430285920, 0xc430285920, 0xc433eaa001, 0x0, 0x2)
        /builds/distributions/dists/go-ipfs/gopath/src/gx/ipfs/QmWzfrG1PUeF8mDpYfNsRL3wh5Rkgnp68LAWUB2bhuDWRL/go-libp2p-transport/tcp.go:187 +0x1ce
gx/ipfs/QmWzfrG1PUeF8mDpYfNsRL3wh5Rkgnp68LAWUB2bhuDWRL/go-libp2p-transport.(*tcpDialer).Dial(0xc4203441c0, 0x10ec0c0, 0xc430285920, 0x10e2020, 0xc4203441c0, 0xc420766688, 0x438173)
        /builds/distributions/dists/go-ipfs/gopath/src/gx/ipfs/QmWzfrG1PUeF8mDpYfNsRL3wh5Rkgnp68LAWUB2bhuDWRL/go-libp2p-transport/tcp.go:163 +0x4f
gx/ipfs/QmVCe3SNMjkcPgnpFhZs719dheq6xE7gJwjzV7aWcUM4Ms/go-libp2p/p2p/net/conn.(*Dialer).rawConnDial(0xc42004b360, 0x10e8aa0, 0xc424671500, 0x10ec0c0, 0xc430285920, 0xc443ae6690, 0x22, 0xc42d42da00, 0x0, 0x1, ...)
        /builds/distributions/dists/go-ipfs/gopath/src/gx/ipfs/QmVCe3SNMjkcPgnpFhZs719dheq6xE7gJwjzV7aWcUM4Ms/go-libp2p/p2p/net/conn/dial.go:155 +0x2c2
gx/ipfs/QmVCe3SNMjkcPgnpFhZs719dheq6xE7gJwjzV7aWcUM4Ms/go-libp2p/p2p/net/conn.(*Dialer).Dial.func1(0xc42663b9e0, 0x10e8aa0, 0xc424671500, 0xc42004b360, 0x10ec0c0, 0xc430285920, 0xc443ae6690, 0x22, 0xc42be625a0, 0xc42be62580)
        /builds/distributions/dists/go-ipfs/gopath/src/gx/ipfs/QmVCe3SNMjkcPgnpFhZs719dheq6xE7gJwjzV7aWcUM4Ms/go-libp2p/p2p/net/conn/dial.go:57 +0xd5
created by gx/ipfs/QmVCe3SNMjkcPgnpFhZs719dheq6xE7gJwjzV7aWcUM4Ms/go-libp2p/p2p/net/conn.(*Dialer).Dial
        /builds/distributions/dists/go-ipfs/gopath/src/gx/ipfs/QmVCe3SNMjkcPgnpFhZs719dheq6xE7gJwjzV7aWcUM4Ms/go-libp2p/p2p/net/conn/dial.go:103 +0x359

goroutine 24191161 [select, 14 minutes]:
gx/ipfs/QmX6DhWrpBB5NtadXmPSXYNdVvuLfJXoFNMvUMoVvP5UJa/go-context/io.(*ctxReader).Read(0xc4395d83c0, 0xc433d85000, 0x1000, 0x1000, 0xd3a2b0, 0xc41ebbd9e0, 0x0)
        /builds/distributions/dists/go-ipfs/gopath/src/gx/ipfs/QmX6DhWrpBB5NtadXmPSXYNdVvuLfJXoFNMvUMoVvP5UJa/go-context/io/ctxio.go:113 +0x2b4
bufio.(*Reader).fill(0xc423e3d1a0)
        /home/whyrusleeping/go/src/bufio/bufio.go:97 +0x10c
bufio.(*Reader).ReadByte(0xc423e3d1a0, 0x0, 0x58, 0x68)
        /home/whyrusleeping/go/src/bufio/bufio.go:231 +0x51
encoding/binary.ReadUvarint(0x10dbde0, 0xc423e3d1a0, 0x0, 0x10e8aa0, 0x97a)
        /home/whyrusleeping/go/src/encoding/binary/varint.go:110 +0x4a
gx/ipfs/QmZ4Qi3GaRbjcx28Sme5eMH7RQjGkt8wHxt2a65oLaeFEV/gogo-protobuf/io.(*varintReader).ReadMsg(0xc433010b40, 0x10e4fe0, 0xc44884c380, 0x0, 0x0)
        /builds/distributions/dists/go-ipfs/gopath/src/gx/ipfs/QmZ4Qi3GaRbjcx28Sme5eMH7RQjGkt8wHxt2a65oLaeFEV/gogo-protobuf/io/varint.go:105 +0x3e
github.com/ipfs/go-ipfs/routing/dht.(*IpfsDHT).handleNewMessage(0xc4200de6e0, 0x10e75e0, 0xc433010b00)
        /builds/distributions/dists/go-ipfs/gopath/src/github.com/ipfs/go-ipfs/routing/dht/dht_net.go:37 +0x48a
created by github.com/ipfs/go-ipfs/routing/dht.(*IpfsDHT).handleNewStream
        /builds/distributions/dists/go-ipfs/gopath/src/github.com/ipfs/go-ipfs/routing/dht/dht_net.go:21 +0x53
```

**Comment by RichardLitt** [comment]
Hey @matthiasbeyer, thanks! This issue doesn't belong in this repository, but rather in [ipfs/support](//github.com/ipfs/support). Please reopen it there! This repo is for high-level conversations about IPFS, while the code you're referring to is in [ipfs/go-ipfs](//github.com/ipfs/go-ipfs), where an issue will be filed if it turns out to be a bug and not some other issue. 

Thank you!
